### ISSUE TITLE
DDBB appliance as GPT Partition Table

### ISSUE THREAD

**Issue by jparrill** [ManageIQ/manageiq-appliance_console#10]
Hi there,

When you try to configure database on a HDD/SSD with a size more than 2 TB, the Appliance_console gives an error:

> Initialize postgresql disk starting
> Initialize postgresql disk failed with error - parted -s /dev/vdf mkpart primary 0% 100% exit code: 1.

In the emv.log you can see:
> appliance_console.log:E, [2017-10-24T13:56:37.146463 #26751] ERROR -- : MIQ(ApplianceConsole::InternalDatabaseConfiguration#initialize_postgresql_disk)  Command failed: parted -s /dev/vde mkpart primary 0% 100% exit code: 1. Error: Error: partition length of 6442448896 sectors exceeds the msdos-partition-table-imposed maximum of 4294967295

The problem here is the appliance console component, by default are defined as msdos part table, we need to set as GPT.

**Comment by Fryguy** [comment]
cc @carbonin

**Comment by bdunne** [comment]
Fixed by #23
