### ISSUE TITLE
Combine Kafka client configuration for external server and ManageIQ server

### ISSUE THREAD

**Issue by jvlcek** [ManageIQ/manageiq-appliance_console#135]
PR [130](https://github.com/ManageIQ/manageiq-appliance_console/pull/130) introduced the ability to configure a ManageIQ appliance as a Kafka message server **and**  to configure a ManageIQ appliance as a Kafka message client to an existing ManageIQ appliance previously configured as a Kafka message server.

Prior to PR [130](https://github.com/ManageIQ/manageiq-appliance_console/pull/130) there already existed the ability to configure a ManageIQ appliance as a Kafka message client to an external, non-ManageIQ, Kafka server.

With PR [130](https://github.com/ManageIQ/manageiq-appliance_console/pull/130) the `Configure Messaging` menu will look like this:

```
Configure Messaging

1) Configure this appliance as a messaging server
2) Connect to an appliance configured as a messaging server
3) Connect to an external messaging system
4) Make No messaging changes
```

This issue will track combining options 2 and 3 above:

```
2) Connect to an appliance configured as a messaging server
3) Connect to an external messaging system
```

into a single option for configuring  the current appliance connected to either an appliance configured as a messaging server or an external messaging system

**Comment by bdunne** [comment]
Other follow-up items:
- [ ] Investigate if logs directory should be moved to `/var/log` https://github.com/ManageIQ/manageiq-appliance_console/pull/130#discussion_r526473961
- [ ] Investigate if there is anything else that can be done to protect the passwords on the command line https://github.com/ManageIQ/manageiq-appliance_console/pull/130/files#r526476752
- [ ] Once client configuration is complete on a server, switch https://github.com/ManageIQ/manageiq/blob/2f8ae2345eb25b16ad87f7dc124b4fe68a610bdb/config/settings.yml#L936 to `kafka`.

**Comment by jvlcek** [comment]
Once client configuration is complete on a server, switch https://github.com/ManageIQ/manageiq/blob/2f8ae2345eb25b16ad87f7dc124b4fe68a610bdb/config/settings.yml#L936 to kafka.

Will be tracked by: https://github.com/ManageIQ/manageiq-appliance_console/issues/136

**Comment by jvlcek** [comment]
Follow-up items:

* [ ]  Investigate if logs directory should be moved to `/var/log` [#130 (comment)](https://github.com/ManageIQ/manageiq-appliance_console/pull/130#discussion_r526473961)

Tracked by Issue: https://github.com/ManageIQ/manageiq-appliance_console/issues/139

* [ ]  Investigate if there is anything else that can be done to protect the passwords on the command line https://github.com/ManageIQ/manageiq-appliance_console/pull/130/files#r526476752

Tracked by Issue: https://github.com/ManageIQ/manageiq-appliance_console/issues/140

* [ ]  Once client configuration is complete on a server, switch Setting to `kafka`

See: https://github.com/ManageIQ/manageiq/blob/2f8ae2345eb25b16ad87f7dc124b4fe68a610bdb/config/settings.yml#L936 to `kafka`.

Tracked by Issue: https://github.com/ManageIQ/manageiq-appliance_console/issues/136

Pull Requests: https://github.com/ManageIQ/manageiq-appliance_console/pull/137
and https://github.com/ManageIQ/manageiq/pull/20837

* [ ] Combine Kafka client configuration for external server and ManageIQ server

Tracked by: https://github.com/ManageIQ/manageiq-appliance_console/issues/135

* [ ] Update appliance_console CLI to enable/disable kafka

Tracked by: https://github.com/ManageIQ/manageiq-appliance_console/issues/142

* [ ] Update appliance_console  kafka client configuration to disable the kafka server

Tracked by: https://github.com/ManageIQ/manageiq-appliance_console/issues/141

* [ ] Create a kick start to build images with the kafka server pre-configured

Tracked by: https://github.com/ManageIQ/manageiq-appliance-build/issues/454

**Comment by agrare** [comment]
Similar to "Investigate if logs directory should be moved to /var/log #130 (comment)" where are we storing the persistent queue messages, should we have another volume dedicated to it?
