### ISSUE TITLE
Configuring kafka on a new appliance warns that kafka is configured already

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-appliance_console#167]
```
Configure Application

Installed file /opt/kafka/config/server.properties found.

Already configured on this Appliance, Un-Configure first? (Y/N):
```

**Comment by bdunne** [comment]
This is expected since ManageIQ appliances are initialized on first boot.  https://github.com/ManageIQ/manageiq-appliance/blob/485dfe59deddbb2d54558368021cba14525247d2/LINK/usr/bin/manageiq-initialize.sh#L6

**Comment by bdunne** [comment]
@agrare Please re-open if you think something else needs to be done here.
