### ISSUE TITLE
Messaging configuration wizard fails if ca-cert file already exists

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-appliance_console#253]
If `/opt/kafka/config/keystore/ca-cert` already exists (and doesn't match the server you want to configure), then the appliance console messaging configuration wizard will always fail. The "Un-Configure" option does not remove or replace the ca-cert file:

```
Stopping ManageIQ Server...
Configure Application

Installed file /opt/kafka/config/client.properties found.
Installed file /var/www/miq/vmdb/config/messaging.yml found.
Installed file /opt/kafka/config/keystore/truststore.jks found.

Already configured on this Appliance, Un-Configure first? (Y/N): Y
Remove Installed Files

~snip~

Checking connectivity to my-kafka-server.localdomain ...
Succeeded.
Configure Messaging Yaml
Create Client Properties
Fetch Truststore From Server
Fetch Ca Cert From Server
	WARNING: /opt/kafka/config/keystore/ca-cert already exists. Taking no action.

Message Client configured successfully.

Starting ManageIQ Server...
```

In this situation I would have expected:
1. If the ca-cert can't be updated, then the wizard should report that configuration failed
2. User should be given either
    - An option to replace the existing ca-cert file
    - Information on how to manually remove the existing ca-cert file before re-running the auto configuration wizard

**Comment by nasark** [comment]
PR for fix https://github.com/ManageIQ/manageiq-appliance_console/pull/258
