### ISSUE TITLE
CTL-C Out of Nested Menus Doesn't Work

### ISSUE THREAD

**Issue by jerryk55** [ManageIQ/manageiq-appliance_console#46]
The interrupt signal handler isn't letting you break out of nested menus - resulting in the need to "kill -9" the process when running appliance_console.

A better method would be to always require the option to return to the previous level when prompting for a selection in a menu.

**Comment by bdunne** [comment]
This appears to be working on a recent master build.  Ctrl-C on the primary menu, a nested menu and an input prompt all bring you back to the summary screen.

Please re-open (with steps to reproduce) if this is still an issue.
