### ISSUE TITLE
5.10 ap is super-slow :(

### ISSUE THREAD

**Issue by d-m-u** [ManageIQ/manageiq-appliance_console#63]
The "Press any key to continue" prompt on 5.10 takes about nine million years to actually respond to anything.

**Comment by carbonin** [comment]
What's a 5.10? Are you seeing this in a stable version of manageiq? Or is this an issue in a nightly build?

**Comment by carbonin** [comment]
Ah this was fixed in https://github.com/ManageIQ/manageiq-appliance_console/pull/56
