### ISSUE TITLE
console_cli 3.3.0 not able to display hammer1 region correctly

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-appliance_console#79]
Hi  @carbonin

Using appliance_console_cli to init appliance and set region is working up until hammer-1 release.

* remove existing db and region by [/root/clean-db.sh](https://gist.github.com/carbonin/a25b84efca2e6b3c3f91b673821a22c8)

```
[root@miqregion01 ~]# cat /root/clean-db.sh
#!/bin/bash
# clean_manageiq.sh
# Stop and disable services

systemctl stop evmserverd && systemctl disable evmserverd
systemctl stop $APPLIANCE_PG_SERVICE && systemctl disable $APPLIANCE_PG_SERVICE

# Remove auto-generated files
if [ -d /var/www/miq/vmdb ]; then
  pushd /var/www/miq/vmdb
    rm -f REGION GUID certs/* config/database.yml
  popd
else
  echo "/var/www/miq/vmdb not found."
  exit 1
fi

# Remove pg database data
if [ -d "$APPLIANCE_PG_DATA" ]; then
  pushd $APPLIANCE_PG_DATA
  rm -rf ./*
  popd
else
  echo "$APPLIANCE_PG_DATA not found"
fi

exit 0

[root@miqregion01 ~]#

```
* init db 
```
host="miqregion01.test.lan"
appliance_console_cli --internal -h ${host} --standalone --key  --username=root --password=smartvm
```
*  set the region
```
host="miqregion01.test.lan"
region=1
appliance_console_cli -h ${host} --region=${region}  --username=root --password=smartvm  --fetch-key=${host}  --sshlogin=root --sshpassword=smartvm

```
Please see details at [following test result in gdoc](https://docs.google.com/document/d/1b5NNbeLMJBI9bG_4GJRjl7ZLphjLYaxDBIheVGP99a8/edit#heading=h.9qnjggkogr4e).

* cli version used in hammer-1 is 3.0.3
```
[root@miqregion01 vmdb]# grep manageiq-appliance_console Gemfile*
Gemfile.lock:    manageiq-appliance_console (3.3.0)
Gemfile.lock:  manageiq-appliance_console (~> 3.3)
[root@miqregion01 vmdb]#

```

Please review gdoc  and provide pointer if you can.

Thanks

**Comment by tjyang** [comment]
* Same cli commands was able to set region correctly to region 1

```
Welcome to the ManageIQ Virtual Appliance.

To modify the configuration, use a web browser to access the management page.

Hostname:                miqregion01
IPv4 Address:            192.168.1.75/255.255.255.0
IPv4 Gateway:            192.168.1.1
IPv6 Address:            2601:248:104:7159:20c:29ff:fe67:72b4/64
IPV6 Gateway:            fe80::6238:e0ff:fe0a:f1
Primary DNS:             192.168.1.40
Secondary DNS:           192.168.1.1
Search Order:            test.lan
MAC Address:             00:0c:29:67:72:b4
Timezone:                America/New_York
Local Database Server:   running (primary)
ManageIQ Server:         running
ManageIQ Database:       miqregion01.test.lan
Database/Region:         vmdb_production / 1
External Auth:           not configured
ManageIQ Version:        gaprindashvili-7


Press any key to continue.

```

**Comment by tjyang** [comment]
* Issue looks like is on console_cli side, since miq classic GUI does display the region number correctly in Hammer-1.

![image](https://user-images.githubusercontent.com/378638/51426316-8fa93000-1bae-11e9-95af-1c58f4c791a9.png)

**Comment by carbonin** [comment]
Also, the commands you ran are a bit redundant. It looks like you're first creating a standalone database on a server and generating the key, then creating a region in that database on the same server and fetching the key from the local host? You could do all of that in one command with this:

```
region=1
appliance_console_cli --internal --region ${region} --key --password=smartvm
```

And that is, incidentally, exactly what we run to initialize the appliance on first boot and that seems to be working.

**Comment by carbonin** [comment]
Okay, so are you just reporting that the appliance console summary screen shows region 0 when it should be region 1?

If so, I think this is the issue:

```
irb(main):008:0> MiqRegion.my_region.region_id
=> 1
irb(main):009:0> ManageIQ::ApplianceConsole::DatabaseConfiguration.region.to_i
=> 0
irb(main):010:0> ManageIQ::ApplianceConsole::DatabaseConfiguration.region
=> "** ManageIQ hammer-1, codename: Hammer\n1"
```

It looks like adding the codename line is causing the parsing of the region id to fail for the console gem.

**Comment by carbonin** [comment]
Specifically in this method: https://github.com/ManageIQ/manageiq-appliance_console/blob/ca279296f1a926c7db6a22cc56b6312db92dc767/lib/manageiq/appliance_console/utilities.rb#L36-L52
